language: ruby
cache:
- bundler
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: i+qNP4RyTOK9z9h3Cf8MhfAVawn3OXhxu0VeLsaJ66tQB9/g26tCL/gfBKfhOSgDRB78zWBqe7CFMZ7TYBIaryW7Fl5ku5UzKC7dneU5wqdsRV399P2hWxVICjYgfBvM9GrGfn+CU83w6a2hqd1JimLdH/KeBDwOb764eIMIEIQfBgvIfbWOcSxrU7qenqzMTZ/+uh1z+UkMnYdB3weae9NXZu9vj8eVuyX1bwoi1cVE32P5zOM/Vxpjqqo9KgdDjXzG1yX3pXlTUAnNbPz/a4WoSQJ3PLdT1TXlARm0p9ePB9JQZvTYCdXbV1TPzSNc9QZYcMrPyQsiDqmxGRl7IAvwulLVqyiS1Exf/9C0Z0jHFjGQa3Le0P4c5aNrmj4Hmr18qpLaoDRO/cqyMo25FObaekcvLEPgmrAV39KB1NV4/2iSo89eztSxEEs5Kfq6BOHV6Pd30biUgT6KzlY/Rau3z5jhAEodxC7qv6JDqajFwdFxNG/3Do+kSXsxmSbVTkO7DaTnqGzQRnP8klKxXT4HdBQT6MP2cnB0XRZbCT7mr4BIB80bbT5vuJICDK/humMSioqeituwg4WzJ/r+W/Pq9w7dED1quB9Eu4ecJnnOVWhRWTfjiEJtMIM6GvMMhchfdjHTMD6SZ72YIJv1ypaU+FIKldaWsnhryGIJSrs=
  app: rails-test-app-article
  on:
    repo: felipeluizsoares/rails-test-app