language: ruby
os:
- linux
dist: xenial
cache:
  bundler: true
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
deploy:
  provider: heroku
  api_key:
    secure: A7rMGkOgRu5d7N6M2LidqEwmj9ogC7AMb3J04OHpz8gbwWK6roylLENGTDcz1sx+ngYqAFPyDXnYmzKw7O13uw+SWsvlM7YoUspkuCu82TeXK7+9UPrevJh6b6tKBqHMQfvrGME91nQT4gCWxCIEvw13vAF9xzmjtUR6Y1M+pBBHW+kly+Ql7omTPFrzIgLVpvyAT1Lv3utTYrrWrc+n3QiiIlPfaYpBJ4g2UpR4UeGEwcMRCqHIYge6NDsUDw3hW4vCCCHq3krH2ioZb90XT3vX6GQ6FdcUfSDfnzb5yrRc3UvmpSWJvZuIw7uJThhHmg8gxsTlbG7VOjDaBWuGGrzL48zopKdkByu19gr0pHIXD6+OvkICSp+E6KvnTfSmsj0R/vMAJc4FS/qjIlNMCDOWQ/o4iexa+xuS4c7bqaqFpH7fBdrZjoLtfDr5DHoF8lG/gpcz1VdI/lQr5ZJ0IMJp2p6qwGiKp0y9YF9mWR9yTb2hrqTRuBn/Tfe+hreeo6bal5Y8LF0xv/CVTlCTwzZvzL4jpC8sJZGP/S1YuP4DyfNAbDfHMgddqUw/oMd9mnSCjsXHqFwk0HLrn5OhbtEJ8EIoTzlkU9yDitXtkuDphItz2yeeNHoniBNqzi3d6EM3nY7a5J13nX2H6t60TncnFnur4EIrRO39V3cF09k=
  strategy: api
  app: second-life-app
  on:
    repo: jarasmar/Second_Life
  